[build]
  publish = "public"
  functions = "netlify/functions"

[functions."compile-pdf"]
  timeout = 26

[[redirects]]
  from = "/api/summarize"
  to = "/.netlify/functions/summarize"
  status = 200

[[redirects]]
  from = "/api/latex-only"
  to = "/.netlify/functions/latex-only"
  status = 200

[[redirects]]
  from = "/api/compile-pdf"
  to = "/.netlify/functions/compile-pdf"
  status = 200
